name = "worker-shortener-domain"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
routes = [{ pattern = "jli.li/*", zone_name = "jli.li" }]

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "<hyperdrive-id-here>"
localConnectionString = "postgres://user:0000@localhost:1234/test"
